test actions as part of PR

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -2,8 +2,11 @@ name: Release Pipeline
 
 on:
   push:
-    tags:
-      - '**'
+    # TODO remove
+    branch: "benchmark"
+    # TODO uncomment
+    #tags:
+    #  - '**'
 
 
 env:
@@ -15,11 +18,14 @@ jobs:
     if: github.repository == 'opendp/tumult-analytics'
     runs-on: ubuntu-latest
     steps:
-      - run: |
-          if [[ ! "$GITHUB_REF_NAME" =~ ^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-(dev|alpha|beta|rc)\.(0|[1-9][0-9]*))?$ ]]; then 
-            echo "Tag $GITHUB_REF_NAME is not a valid version number. Aborting release pipeline."
-            exit 1
-          fi
+      # TODO remove
+      - run: /usr/bin/true
+      # TODO uncomment
+      #- run: |
+      #    if [[ ! "$GITHUB_REF_NAME" =~ ^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-(dev|alpha|beta|rc)\.(0|[1-9][0-9]*))?$ ]]; then 
+      #      echo "Tag $GITHUB_REF_NAME is not a valid version number. Aborting release pipeline."
+      #      exit 1
+      #    fi
 
   Package:
     if: github.repository == 'opendp/tumult-analytics'
